// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imjtxoeceoipwxrjmlof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltanR4b2VjZW9pcHd4cmptbG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjYyMzYsImV4cCI6MjA2MzcwMjIzNn0.3JUJSDgZFYjPMpUK4JyKn-cmwDlX_lFSrD0lIFsQeHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);